#include "Arduino.h"
int led = 13;

void setup()
{
	pinMode(13, OUTPUT);
}

void loop(){
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
}
