// #include "Arduino.h"
int LED_;

void setup(){
    LED_ = 13;
	pinMode(LED_, OUTPUT);
}

void loop(){
	digitalWrite(LED_, HIGH);
	delay(200);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(600);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(600);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(600);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(600);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, LOW);
	delay(600);
	digitalWrite(LED_, HIGH);
	delay(200);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(200);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(600);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(600);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(600);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, LOW);
	delay(600);
	digitalWrite(LED_, HIGH);
	delay(200);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(200);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(200);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(600);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(600);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, LOW);
	delay(600);
	digitalWrite(LED_, HIGH);
	delay(200);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(200);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(200);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(200);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(600);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, LOW);
	delay(600);
	digitalWrite(LED_, HIGH);
	delay(200);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(200);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(200);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(200);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(200);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, LOW);
	delay(600);
	digitalWrite(LED_, HIGH);
	delay(600);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(200);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(200);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(200);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(200);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, LOW);
	delay(600);
	digitalWrite(LED_, HIGH);
	delay(600);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(600);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(200);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(200);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(200);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, LOW);
	delay(600);
	digitalWrite(LED_, HIGH);
	delay(600);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(600);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(600);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(200);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(200);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, LOW);
	delay(600);
	digitalWrite(LED_, LOW);
	delay(600);
	digitalWrite(LED_, HIGH);
	delay(600);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(600);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(600);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(600);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(600);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, LOW);
	delay(600);
	digitalWrite(LED_, LOW);
	delay(600);
	digitalWrite(LED_, HIGH);
	delay(600);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(200);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(200);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(200);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, LOW);
	delay(600);
	digitalWrite(LED_, HIGH);
	delay(200);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, HIGH);
	delay(600);
	digitalWrite(LED_, LOW);
	delay(100);
	digitalWrite(LED_, LOW);
	delay(600);
}
