/*
  WeihnachtsMorse :)
  Uses given morse code representation to turn the leds on and off to send the message using Morse Codes.
  First the morse code must be generated using Morse.cpp.
 */
 
// Using Pin.
int led = 13;

// the setup routine runs once when you press reset:
void setup() {                
  // initialize the digital pin as an output.
  pinMode(led, OUTPUT);
}

// the loop routine runs over and over again forever:
void loop() {
  for(int i=0; i<10;i++)
    {
		digitalWrite(led, HIGH);
		delay(50);
		digitalWrite(led, LOW);
		delay(50);
    }
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(600);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
	digitalWrite(led, HIGH);
	delay(200);
	digitalWrite(led, LOW);
	delay(100);
	digitalWrite(led, LOW);
	delay(600);
}
